/*
 * Server side (written by user): procedure name is that given on sort.x
 * appended version number (_1) and _svc in this order. This function prototype
 * is used on files generated by rpcgen.
 *
 * compile with gcc (after rpcgen):
 *      gcc -o server server.c square_svc.c square_xdr.c -lrpcsvc
 */

#include	"sort.h"

sort_out *sortproc_1_svc(sort_in *inp, struct svc_req *rqstp) {
    static sort_out out;
	int i,n;
	for (i = 0; i < 250; i++)
		out.res1[i] = inp->arg1[i];
	for (n = 0; n < 250; n++)
		for (i = 0; i < 250 - n - 1; i++)
			if (out.res1[i] < out.res1[i+1]) {
				int temp = out.res1[i];
				out.res1[i] = out.res1[i+1];
				out.res1[i+1] = temp;
			}
    return(&out);
}
