/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NULL_H_RPCGEN
#define _NULL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define NIL_PROG 0x31230001
#define NIL_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define NILPROC 1
extern  void * nilproc_1(void *, CLIENT *);
extern  void * nilproc_1_svc(void *, struct svc_req *);
extern int nil_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define NILPROC 1
extern  void * nilproc_1();
extern  void * nilproc_1_svc();
extern int nil_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NULL_H_RPCGEN */
